version: '3.8'

services:
  frontend:
    build:
      context: .
    ports:
      - "3000:3000"  # Map port 3000 on the container to port 3000 on the host
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules  # Avoid mounting node_modules to prevent potential issues
